import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// header and footer
import Footer from "@/components/shared/Footer"
import Header from "@/components/shared/Header"

// dark mode
import { ThemeProvider } from "@/components/theme-provider"

// rainbowkit provider, including wagmi, viem...
import RainbowkitProvider from "./RainbowkitProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DLivret",
  description: "Generated by create next app", // usefull for SEO
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RainbowkitProvider>
          <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
            <div className="app">
              <Header />
                <main className="main">
                  {children}
                </main>
                <Toaster />
              <Footer />
            </div>
          </ThemeProvider>
        </RainbowkitProvider>
      </body>
    </html>
  );
}
