import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// header and footer
import Footer from "@/components/shared/Footer"
import Header from "@/components/shared/Header"

// dark mode
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DLivret",
  description: "Generated by create next app", // usefull for SEO
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
          <div className="app">
            <Header />
              <main className="main">
                {children}
              </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
