name: Contract tests

on:
  push:
    branches: [master]

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          touch .env
          echo ALCHEMY_MAINNET_RPC=${{ secrets.ALCHEMY_MAINNET_RPC }} >> .env
          echo COINMARKETCAP_API_KEY=${{ secrets.COINMARKETCAP_API_KEY }} >> .env
          echo ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} >> .env

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: node_modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npx hardhat test